sudo: false

language: php

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0
      env:
        - EXECUTE_COVERAGE=true
    - php: hhvm
  allow_failures:
    - php: hhvm

notifications:
  email: false

before_install:
  - phpenv config-rm xdebug.ini || return 0
  - mkdir -p ./build/logs || return 0

install:
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  # PHPUnit
  - if [[ $EXECUTE_COVERAGE == 'true' ]]; then phpdbg -qrr ./vendor/bin/phpunit --coverage-text --coverage-clover=./build/logs/clover.xml ; fi
  - if [[ $EXECUTE_COVERAGE != 'true' ]]; then ./vendor/bin/phpunit ; fi
  # PHP CS Fixer
  - if [[ EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/php-cs-fixer fix -v --dry-run ; fi

after_script:
  - if [[ $EXECUTE_COVERAGE == 'true' ]]; then ./vendor/bin/ocular code-coverage:upload --format=php-clover ./build/logs/clover.xml; fi
